### ISSUE TITLE
Cython

### ISSUE THREAD

**Issue by onaclov2000** [davesarmoury/GLaDOS#3]
When I installed the requirements at the top of the Train_NeMo jupyter notebook (in cell one), it failed on "youtokenme", I then ran the install outside of jupyter and it had issues with cython at the same point, so I had to install that separately, not sure if it needs to be added to requirements.txt (or why the nemo_toolkit[all] didn't find that as a dependency) but I just wanted to mention/share it.

I enjoyed the video thanks for sharing! (That's how I found the repo).

**Comment by davesarmoury** [comment]
Good catch.  Updated requirements
