### ISSUE TITLE
Code Lines Not Recognized In The First Cell

### ISSUE THREAD

**Issue by TheOneTader** [davesarmoury/GLaDOS#4]
I have been trying to run this for a while now and I just can't figure it out, I might be doing something wrong or there could be some outdated files, I don't know. Let me try to explain what I'm trying to achieve and then maybe the problems I'm having might make more sense.

I have been trying to train a Wheatley voice, I just need it to work on my PC, I put in text and it spits out files for me. Basic TTS.
 So I installed Jupyter, create to files so I know where every thing is, and I start trying to run the cells.(I want to point out that in the readme, under "Training Your Own Voice" it says "Uncommenting the install lines in the first cell _should_ install everything needed, but that isn't guaranteed.", emphasis on the should. Maybe this is the problem, again I have no clue)
  After I have a notebook running(I'm sure that the kernel it runs on is critical but I'm don't know which one to use so its just running with the "Python 3(ipykernel)") I go to the Train_NeMo.ipynb and start trying to run the cells. The first cell
  I run the first one, the "
   #!apt install sox libsndfile1 ffmpeg
   #!pip3 install wheel
   #!pip3 install -r requirements.txt
   #!pip3 install nemo_toolkit[all]
" and nothing happens. Then I realized that I need to drop the "#" at the start of each line. I run it again and this time it does somethings.
  The first thing it says is " 'apt' is not recognized as an internal or external command, operable program or batch file. ".
The next thing it says is " ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' ".
Not knowing what to do with this I try running the next cells anyway and some parts of them work, and other parts saying there were missing requirements.

I'm not to experienced with Jupyter or at all acquainted with training AI voice models but if someone could walk me through how to get this working I would really appreciate it.

**Comment by TheOneTader** [comment]
I also just now realized that there is also a problem with a module called "Cython", Not to sure what that's about.

**Comment by davesarmoury** [comment]
What operating system are you using?  APT is specific to debian systems (like ubuntu)

**Comment by TheOneTader** [comment]
I've been running the whole thing in Windows 11.

**Comment by davesarmoury** [comment]
All commands that start with an ! are run in a terminal, so they are operating system specific. You can leave them commented out, then run them manually in a terminal with a command that matches your OS

**Comment by TheOneTader** [comment]
Thank you, I'll give it a try and then get back to you.

**Comment by TheOneTader** [comment]
Ok, I found a command to use in my terminal that works with my OS.
I started installing everything, SoX installed correctly and so did wheel.
When I got to the requirements.txt I could not get it to work in my terminal, so I opened the txt files and started running the install commands manually and they all worked except for "num2words".
 I also try to install it with a different name "numtowords" and that installed something, and I then went to the 4th cell(The one that starts with "import requests"), changed all the "num2words" to "numtowords" hoping it might magically work and go figure it didn't.
 Maybe num2words is outdated or simply had a name change, I'm not sure.

I also could not get the "pip3 install nemo_toolkit[all]" to install either but all the cells up until 4 worked with out it, and it might not even be an issue.

**Comment by TheOneTader** [comment]
I managed to install num2words and run the cell, the next cell is "!head -n 1 ./audio/manifest.json".
 I ran "head -n 1 ./audio/manifest.json" in my terminal and head was unrecognized, is it maybe a similar issue to apt not working on windows?

**Comment by TheOneTader** [comment]
I was able to fix the last issue with the path, now I'm stuck on the cell that starts with "sup_data_path = './fastpitch_sup_data'", I just don't get what to do with those last few code lines.

**Comment by davesarmoury** [comment]
The command that has "head" in it is a window specific issue. This will print the first line in that file. You can ignore it as it isn't important, just debugging

The sup_data_path line is setting a variable to a directory. It shouldn't have any problems because that is python, not OS specific

Sorry, since I don't usually use windows for this kind of stuff, the notebook isn't set up for it and debugging is tricky

**Comment by TheOneTader** [comment]
Not a problem at all, windows really is its own can of worms. I'm going to take from it for a few days and come back with a clear head and go through all the errors again. Thank you for all your help so far.
