### ISSUE TITLE
Confusing bit in TrainNeMo.ipynb

### ISSUE THREAD

**Issue by onaclov2000** [davesarmoury/GLaDOS#5]
In TrainNemo.ipynb there are the following lines:

!cat ./audio/manifest.json | tail -n 5 > ./manifest_validation.json
!cat ./audio/manifest.json | head -n -5 > ./manifest_train.json

There are somewhere close to 200 files downloaded from the dataset earlier, but it appears that only 5 train and 5 test examples are used for training....am i missing something?

Maybe it doesn't matter, but just found it odd when i was playing with this repo earlier this year.

(I've moved onto other voice cloning stuff, but wanted to at least ask/mention this in case it was accidental)

**Comment by davesarmoury** [comment]
That can be adjusted based on dataset size.  For 200 samples, 20 is probably a decent starting estimate.  5 is low, but should work
